# Interactive component

It is clearly that the data about the radioactive materials (Iodine-131, Caesium-134, and Caesium-137) is worldwide. You might think this is a little weird since it would be plausible if we could get to know the situations around Chernobyl. The reason we use worldwide data is that the only nearby data we could find is the measurements of contamination of Caesium-134 and Caesium-137 near Chernobyl for several dates between 1995-07-28 and 2002-04-20. It is very difficult to display some meaning results by using this dataset since the dates are too sparse. The ideal situation is to use data collected near Chernobyl, but it is not suitable in our situation. However, by using interative map, we would be able to show you the situations.

First, this is a map shows the locations near Chernobyl and you can see it clearly in the plot. You can zoom in or out use the button on the top-left corner. Then the date widget allows you to choose date and we disabled the button for unavailable dates (those are grey). You can choose the date you want and the type of radionuclide you want, and then a marker and a circle would appear for each data point. The marker is lightgray for Caesium-134 and beige for Caesium-137. The circle would be red if the contamination exceeds the mean value (16.79925 for Caesium-134 and 1119.508 for Caesium-137). When your mouse is on the marker, it will show the contamination and the unit is kilo bequerels per metre squared. As we can see, the contamination near Chernobyl is very serious. 
